In [10]:
from solution_simulator import game, goal, dies, solve
from pprint import pprint
import numpy as np

In [11]:
goal.shape

(4, 6)

In [12]:
game

array([[2, 2, 0, 1, 0, 3],
       [2, 1, 3, 0, 3, 3],
       [0, 2, 2, 1, 0, 3],
       [3, 2, 2, 0, 3, 3]])

In [18]:
step1 = solve['ops'][2]
p_die = step1['p']
die = dies[p_die] # p_die
x = step1['x']
y = step1['y']
s = step1['s']

print(f"Die {p_die} at ({x}, {y}) to {s}")
print(die)

Die 25 at (3, 3) to 0
[[0 1 1 1]
 [1 0 0 1]]


In [27]:
def get_point(game: np.ndarray, die: np.ndarray, x: int, y: int) -> tuple:
    '''
    Get the point of the die in the game
    
    Args:
        game (np.ndarray): the game game
        die (np.ndarray): the die
        x (int): the x coordinate
        y (int): the y coordinate
    
    Returns:
        tuple: the x_start, y_start, x_end, y_end
    '''
    h, w = game.shape
    _h, _w = die.shape
    x_end = min(x + _w, w)
    y_end = min(y + _h, h)
    x_start, y_start = max(x, 0), max(y, 0)

    return x_start, y_start, x_end, y_end


x1, y1, x2, y2 = get_point(game, die, x, y)
print(x1, y1, x2, y2)
A = game[y1:y2, x1:x2]
print(A)

3 3 6 4
[[0 3 3]]


In [20]:
def lift_elements(A: np.ndarray, die: np.ndarray) -> np.ndarray:
    '''
    Lift the elements of the die in the game
    
    Args:
        A (np.ndarray): the game game
        die (np.ndarray): the die
        
    Returns:
        np.ndarray: the lifted elements
    '''
    h, w = A.shape
    die = die[:h, :w]
    res = np.zeros(A.shape, dtype=int)-1
    pos_1 = np.where(die == 1)
    res[pos_1] = A[pos_1]
    return res, pos_1

lift_elements(A, die)

(array([[-1,  3,  0,  3],
        [ 2, -1, -1,  0]]),
 (array([0, 0, 0, 1, 1]), array([1, 2, 3, 0, 3])))

In [30]:
def die_cut(game: np.ndarray, die: np.ndarray, x: int, y: int, d: int) -> np.ndarray:
    '''
    Cut the die in the game

    Args:
        game (np.ndarray): the game game
        die (np.ndarray): the die
        x (int): the x coordinate
        y (int): the y coordinate
        d (int): the d (0-top, 1-bottom, 2-left, 3-right)

    Returns:
        np.ndarray: the cut die
    '''
    height, width = game.shape
    x1, y1, x2, y2 = get_point(game, die, x, y)
    A = game[y1:y2, x1:x2]
    L, P = lift_elements(A, die)
    P_ = (P[0] + y1, P[1] + x1)
    game[P_] = -1
    if d>1:
        for r in range(y1, y2):
            col1 = [game[r][i] for i in range(width) if game[r][i] != -1]
            col2 = [L[r-y1][i] for i in range(len(L[r-y1])) if L[r-y1][i] != -1]
            if d == 3: # right
                col = np.concatenate((col1, col2))
                # game[r] = col
            elif d == 2: # left
                col = np.concatenate((col2, col1))
                # game[r] = col
    else:
        for c in range(x1, x2):
            row1 = [game[i][c] for i in range(height) if game[i][c] != -1]
            print(f'{row1=}')

            row2 = [L[i][c-x1] for i in range(len(L)) if L[i][c-x1] != -1][::-1]
            print(f'{row2=}')
            if d == 1: # bottom
                row = np.concatenate((row1, row2))
                print(row)
                # game[:, c] = row
            elif d == 0: # top
                row = np.concatenate((row2, row1))
                print(row)
                game[:, c] = row

    return game

test = game.copy()
test = die_cut(test, die, x, y, s)
test

row1=[np.int64(1), np.int64(0), np.int64(1), np.int64(0)]
row2=[]
[1. 0. 1. 0.]
row1=[np.int64(0), np.int64(3), np.int64(0)]
row2=[np.int64(3)]
[3 0 3 0]
row1=[np.int64(3), np.int64(3), np.int64(3)]
row2=[np.int64(3)]
[3 3 3 3]


array([[2, 2, 0, 1, 3, 3],
       [2, 1, 3, 0, 0, 3],
       [0, 2, 2, 1, 3, 3],
       [3, 2, 2, 0, 0, 3]])

In [22]:
game

array([[2, 2, 0, 1, 0, 3],
       [2, 1, 3, 0, 3, 3],
       [0, 2, 2, 1, 0, 3],
       [3, 2, 2, 0, 3, 3]])

In [25]:
test

array([[2, 2, 2, 1, 0, 3],
       [1, 3, 0, 3, 2, 3],
       [2, 2, 0, 3, 0, 3],
       [2, 0, 1, 0, 3, 3]])

In [13]:
x = ([0, 0, 1, 3], [2, 3, 4, 2])

k = {}
for i, j in zip(*x):
    k[i] = k.get(i, []) + [j]
k

{0: [2, 3], 1: [4], 3: [2]}

In [25]:
a=[0, 0, 1, 0]
a.pop(0)
a

[0, 1, 0]

In [9]:
game[(0, 0), (1, 2)]

array([2, 0])