In [1]:
from src.envs.utils import apply_die_cutting

In [2]:
import numpy as np

board = np.array([
    [1, 0, 1, 1, 2, 2, 1],
    [2, 3, 1, 1, 0, 0, 2],
    [3, 0, 2, 1, 1, 1, 1],
    [3, 0, 0, 2, 2, 3, 1],
    [2, 2, 3, 2, 0, 2, 2],
    [3, 3, 1, 0, 3, 2, 3]
])

print(board.shape) # row, col == h, w

die = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [1, 1, 0]
])

print(die.shape) # row, col == h, w

(6, 7)
(3, 3)


In [4]:
applyBoard = apply_die_cutting(board, die, 0, 0, 2)
applyBoard

array([[1, 1, 1, 2, 2, 1, 0],
       [3, 1, 0, 0, 2, 2, 1],
       [2, 1, 1, 1, 1, 3, 0],
       [3, 0, 0, 2, 2, 3, 1],
       [2, 2, 3, 2, 0, 2, 2],
       [3, 3, 1, 0, 3, 2, 3]])

In [9]:
top_0_0 = np.array([[1, 3, 1, 1, 2, 2, 1],
                    [3, 0, 2, 1, 0, 0, 2],
                    [2, 2, 0, 1, 1, 1, 1],
                    [3, 3, 3, 2, 2, 3, 1],
                    [2, 0, 1, 2, 0, 2, 2],
                    [3, 0, 1, 0, 3, 2, 3]])


bot_0_0 = np.array([[2, 0, 1, 1, 2, 2, 1],
                    [3, 0, 1, 1, 0, 0, 2],
                    [1, 3, 2, 1, 1, 1, 1],
                    [3, 0, 0, 2, 2, 3, 1],
                    [2, 2, 3, 2, 0, 2, 2],
                    [3, 3, 1, 0, 3, 2, 3]])



left_0_0 = np.array([[1, 1, 1, 2, 2, 1, 0],
                     [3, 1, 0, 0, 2, 2, 1],
                     [2, 1, 1, 1, 1, 3, 0],
                     [3, 0, 0, 2, 2, 3, 1],
                     [2, 2, 3, 2, 0, 2, 2],
                     [3, 3, 1, 0, 3, 2, 3]])



right_0_0 = np.array([[0, 1, 1, 1, 2, 2, 1],
                      [2, 1, 3, 1, 0, 0, 2],
                      [3, 0, 2, 1, 1, 1, 1],
                      [3, 0, 0, 2, 2, 3, 1],
                      [2, 2, 3, 2, 0, 2, 2],
                      [3, 3, 1, 0, 3, 2, 3]])

# top

In [ ]:
top_board  = apply_die_cutting(board, die, 0, 0, 0) 
top_board == top_0_0

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# bottom

In [11]:
bot_board= apply_die_cutting(board, die, 0, 0, 1) 
bot_board == bot_0_0

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# left

In [12]:
board_left = apply_die_cutting(board, die, 0, 0, 2)
board_left == left_0_0

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# right

In [13]:
board_right = apply_die_cutting(board, die, 0, 0, 3)
board_right == right_0_0

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])