In [ ]:
from utils import apply_die_cutting

In [16]:
import numpy as np

board = np.array([
    [1, 0, 1, 1, 2, 2, 1],
    [2, 3, 1, 1, 0, 0, 2],
    [3, 0, 2, 1, 1, 1, 1],
    [3, 0, 0, 2, 2, 3, 1],
    [2, 2, 3, 2, 0, 2, 2],
    [3, 3, 1, 0, 3, 2, 3]
])

print(board.shape) # row, col == h, w

die = np.array([
    [0, 1, 0],
    [1, 0, 1],
    [1, 1, 0]
])

print(die.shape) # row, col == h, w

(6, 7)
(3, 3)


In [6]:
top = np.array([
    [1, 0, 1, 1, 2, 2, 1],
    [2, 3, 1, 1, 0, 0, 2],
    [3, 0, 0, 1, 1, 1, 1],
    [3, 3, 1, 2, 2, 3, 1],
    [2, 0, 2, 0, 0, 2, 2],
    [3, 2, 3, 2, 3, 2, 3]
])

bottom = np.array([
    [1, 0, 2, 2, 2, 2, 1],
    [2, 2, 3, 1, 0, 0, 2],
    [3, 0, 1, 1, 1, 1, 1],
    [3, 3, 1, 1, 2, 3, 1],
    [2, 0, 0, 2, 0, 2, 2],
    [3, 3, 1, 0, 3, 2, 3]
])

left = np.array([
    [1, 0, 1, 1, 2, 2, 1],
    [2, 3, 1, 1, 0, 0, 2],
    [3, 0, 1, 1, 1, 1, 2],
    [3, 0, 2, 3, 1, 0, 2],
    [2, 2, 0, 2, 2, 2, 3],
    [3, 3, 1, 0, 3, 2, 3]
])

right = np.array([
    [1, 0, 1, 1, 2, 2, 1],
    [2, 3, 1, 1, 0, 0, 2],
    [2, 3, 0, 1, 1, 1, 1],
    [0, 2, 3, 0, 2, 3, 1],
    [2, 3, 2, 2, 0, 2, 2],
    [3, 3, 1, 0, 3, 2, 3]
])

# top

In [8]:
apply_die_cutting(board, die, 1, 2, 0) 

board

array([[1, 0, 1, 1, 2, 2, 1],
       [2, 3, 1, 1, 0, 0, 2],
       [3, 0, 0, 1, 1, 1, 1],
       [3, 3, 1, 2, 2, 3, 1],
       [2, 0, 2, 0, 0, 2, 2],
       [3, 2, 3, 2, 3, 2, 3]])

In [9]:
board == top

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# bottom

In [11]:
apply_die_cutting(board, die, 1, 2, 1) 

board

array([[1, 0, 2, 2, 2, 2, 1],
       [2, 2, 3, 1, 0, 0, 2],
       [3, 0, 1, 1, 1, 1, 1],
       [3, 3, 1, 1, 2, 3, 1],
       [2, 0, 0, 2, 0, 2, 2],
       [3, 3, 1, 0, 3, 2, 3]])

In [12]:
board == bottom

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# left

In [14]:
apply_die_cutting(board, die, 1, 2, 2) 

board

array([[1, 0, 1, 1, 2, 2, 1],
       [2, 3, 1, 1, 0, 0, 2],
       [3, 0, 1, 1, 1, 1, 2],
       [3, 0, 2, 3, 1, 0, 2],
       [2, 2, 0, 2, 2, 2, 3],
       [3, 3, 1, 0, 3, 2, 3]])

In [15]:
board == left

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

# right

In [17]:
apply_die_cutting(board, die, 1, 2, 3) 

board

array([[1, 0, 1, 1, 2, 2, 1],
       [2, 3, 1, 1, 0, 0, 2],
       [2, 3, 0, 1, 1, 1, 1],
       [0, 2, 3, 0, 2, 3, 1],
       [2, 3, 2, 2, 0, 2, 2],
       [3, 3, 1, 0, 3, 2, 3]])

In [18]:
board == right

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])